# Generated by Django 5.0.1 on 2024-03-09 16:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'application")),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Image principale')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promo')),
                ('in_promo', models.BooleanField(default=False, verbose_name='En promo')),
                ('is_new', models.BooleanField(default=True, verbose_name='Nouvelle application')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du développeur')),
            ],
            options={
                'verbose_name': 'Développeur',
                'verbose_name_plural': 'Développeurs',
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images/', verbose_name='image supplémentaire')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_image_set', to='app_store.application', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'image supplémentaire',
                'verbose_name_plural': 'images supplémentaires',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='application',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_store.developer', verbose_name='Développeur'),
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, null=True, verbose_name='Mot clé')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_set', to='app_store.application', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Mot clé',
                'verbose_name_plural': 'Mots clés',
            },
        ),
    ]
