# Generated by Django 5.0.1 on 2024-03-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_alter_application_options_application_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='installation_file',
            field=models.FileField(blank=True, null=True, upload_to='installation_files/', verbose_name="Fichier d'installation"),
        ),
    ]
