# Generated by Django 5.0.1 on 2024-03-10 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_application_installation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='download_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Lien de téléchargement'),
        ),
    ]
